import PDFDocument from "pdfkit";

import { addHeader } from "./pdf/header.ts";
import { addExecutiveSummary } from "./pdf/executiveSummary.ts";
import { addPerformance } from "./pdf/performance.ts";
import { addSEO } from "./pdf/seo.ts";
import { addSecurity } from "./pdf/security.ts";
import { addAccessibility } from "./pdf/accessibility.ts";
import { addUXReview } from "./pdf/ux.ts";
import { addBenchmark } from "./pdf/benchmark.ts";
import { addRevenueImpact } from "./pdf/revenue.ts";
import { addActionPlan } from "./pdf/actionPlan.ts";

export type PDFReport = {
  _id: string | { toString(): string };
  url: string;
  createdAt: string | Date;
  report: {
    executiveSummary: Record<string, unknown>;
    performanceAudit: Record<string, unknown>;
    seoAudit: Record<string, unknown>;
    securityAudit: Record<string, unknown>;
    accessibilityAudit: Record<string, unknown>;
    uxUiReview: Record<string, unknown>;
    competitorBenchmark: Record<string, unknown>;
    revenueImpactAnalysis: Record<string, unknown>;
    prioritizedActionPlan: Record<string, unknown>;
  };
};

export const generateReportPDF = async (
  report: PDFReport
): Promise<Buffer> => {
  if (!report) {
    throw new Error("Report not found");
  }

  const audit = report.report;

  const doc = new PDFDocument({
    size: "A4",
    margin: 50,
    bufferPages: true,
    info: {
      Title: `Website Audit Report - ${report.url}`,
      Author: "Web Auditor",
      Subject: "Website Audit",
      Keywords: "SEO, Lighthouse, Security, Accessibility",
      Creator: "Web Auditor",
    },
  });

  const chunks: Buffer[] = [];

  doc.on("data", (chunk) => {
    chunks.push(chunk);
  });

  // -------------------------------------
  // Cover Page
  // -------------------------------------

  addHeader(doc, report);

  // -------------------------------------
  // Executive Summary
  // -------------------------------------

  addExecutiveSummary(
    doc,
    audit.executiveSummary
  );

  // -------------------------------------
  // Performance
  // -------------------------------------

  addPerformance(
    doc,
    audit.performanceAudit
  );

  // -------------------------------------
  // SEO
  // -------------------------------------

  addSEO(
    doc,
    audit.seoAudit
  );

  // -------------------------------------
  // Security
  // -------------------------------------

  addSecurity(
    doc,
    audit.securityAudit
  );

  // -------------------------------------
  // Accessibility
  // -------------------------------------

  addAccessibility(
    doc,
    audit.accessibilityAudit
  );

  // -------------------------------------
  // UX/UI
  // -------------------------------------

  addUXReview(
    doc,
    audit.uxUiReview
  );

  // -------------------------------------
  // Competitor Benchmark
  // -------------------------------------

  addBenchmark(
    doc,
    audit.competitorBenchmark
  );

  // -------------------------------------
  // Revenue Impact
  // -------------------------------------

  addRevenueImpact(
    doc,
    audit.revenueImpactAnalysis
  );

  // -------------------------------------
  // Action Plan
  // -------------------------------------

  addActionPlan(
    doc,
    audit.prioritizedActionPlan
  );

  // -------------------------------------
  // Page Numbers
  // -------------------------------------

  const pages = doc.bufferedPageRange();

  for (let i = 0; i < pages.count; i++) {
    doc.switchToPage(i);

    doc
      .fontSize(9)
      .fillColor("#6B7280")
      .text(
        `Generated by Web Auditor`,
        50,
        doc.page.height - 40
      );

    doc
      .text(
        `Page ${i + 1} of ${pages.count}`,
        0,
        doc.page.height - 40,
        {
          width: doc.page.width - 50,
          align: "right",
        }
      );
  }

  doc.end();

  return await new Promise((resolve, reject) => {
    doc.on("end", () => {
      resolve(Buffer.concat(chunks));
    });

    doc.on("error", reject);
  });
};